### ISSUE TITLE
Syntax Error During configure

### ISSUE THREAD

**Issue by tmose1106** [stoeckmann/xwallpaper#9]
Hello, I was trying to build your project on my Void Linux install, and I ran into the following issue:

```
tedm@tedm-void ~/S/xwallpaper> ./autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
autoreconf: Leaving directory `.'
tedm@tedm-void ~/S/xwallpaper> ./configure 
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for gcc option to accept ISO C99... none needed
checking for gcc option to accept ISO Standard C... (cached) none needed
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking dependency style of gcc... gcc3
./configure: 3878: ./configure: Syntax error: word unexpected (expecting ")")
```

I'm not super sure how to troubleshoot this error, but I thought you might want to know.

**Comment by tmose1106** [comment]
So, I gave it a go on my Arch Linux install, and it worked just fine. From this I realized that the line where the error occurs uses pkg-config. So what I did to fix the error was install pkgconf on my Void installation, and I proceeded to configure again. Problem solved.

I believe the error occured because it attempts to call pkg-config but because it is not found pkg-config is resolved to an empty string or something of the sort, thus the syntax error. There should probably be some kind of check whether pkg-config is actually available and if not it should fail more gracefully. Though I'm not sure how to add that because I've never written any autoconf scripts.

**Comment by stoeckmann** [comment]
I've just added a check into autogen.sh. The pkg-config macro is not resolved, therefore configure cannot run this unknown syntax.

Maybe another reason to switch to meson, as the X.org infrastructure offers that as well...

Thanks for the report. :)
